### ISSUE TITLE
Incorrect subnet syntax in IPAM documentation

### ISSUE THREAD

**Issue by shmcfarl** [contiv/docs#19]
In the "subnet IP pool" section of this page: [http://contiv.github.io/documents/networking/ipam.html](http://contiv.github.io/documents/networking/ipam.html) the example config is incorrect and leads to an error (ERRO[0000] subnet string invalid format):
`netctl net create contiv-net -subnet 10.1.1.50-100/24`

The correct syntax is: 
`netctl net create contiv-net -subnet 10.1.1.50-10.1.1.100/24`
Creating network default:contiv-net

**Comment by stacykor** [comment]
Hi @shmcfarl, thanks for the heads-up. I've moved this issue over to contiv.github.io as this repo is old. It's issue #90 IPAM docs over there.

**Comment by shmcfarl** [comment]
Ah, sorry. I was not sure where to file that.

**Comment by stacykor** [comment]
No worries. Thanks for the feedback:

http://contiv.github.io/documents/networking/ipam.html

This has been updated.
